### ISSUE TITLE
fs storage "does not work"

### ISSUE THREAD

**Issue by majestrate** [majestrate/XD#1]
downloading files "does not work" because something in `xd/lib/storage` stores files "wrong"

**Comment by mathiasfriman** [comment]
I guess this is of no help whatsoever, but I cheer from the bench. Here's a log of one of my test nodes trying to torrent i2pupdate-0.9.29.su3

[xd-log.txt](https://github.com/majestrate/XD/files/812583/xd-log.txt)

Would be really cool to have XD working :) I guess looking at other torrent projects written in go like https://github.com/anacrolix/torrent wouldn't help?

**Comment by majestrate** [comment]
huh, I never knew about that project

**Comment by mathiasfriman** [comment]
Me neither, google is my friend.. :o)

So, after restart of XD, I get this logfile after finishing download of i2pupdate-0.9.29.su3

    [...]
    [DBG] 2017-03-03 17:42:02.093143345 +0100 CET file is 4468421 bytes
    [NFO] 2017-03-03 17:42:02.093213803 +0100 CET verify local data for i2pupdate-0.9.29.su3
    [DBG] 2017-03-03 17:42:02.093305975 +0100 CET hash piece 0 at 65536
    [DBG] 2017-03-03 17:42:02.093786903 +0100 CET piece 0 hash okay
    [DBG] 2017-03-03 17:42:02.093872018 +0100 CET hash piece 1 at 131072
    [DBG] 2017-03-03 17:42:02.094123038 +0100 CET piece 1 hash okay
    [...]
    [DBG] 2017-03-03 17:42:02.117229509 +0100 CET hash piece 67 at 4456448
    [DBG] 2017-03-03 17:42:02.117424876 +0100 CET piece 67 hash okay
    [NFO] 2017-03-03 17:42:02.117503326 +0100 CET i2pupdate-0.9.29.su3 check okay
    [NFO] 2017-03-03 17:42:02.117519096 +0100 CET flush bitfield for 844e6aeb9a1153b28c06eaa0c017469459f0c1a2
    [NFO] 2017-03-03 17:42:02.117636694 +0100 CET added torrent i2pupdate-0.9.29.su3
    [NFO] 2017-03-03 17:42:02.117519096 +0100 CET flush bitfield for 844e6aeb9a1153b28c06eaa0c017469459f0c1a2
    [NFO] 2017-03-03 17:42:02.117636694 +0100 CET added torrent i2pupdate-0.9.29.su3
    [NFO] 2017-03-03 17:42:22.114578523 +0100 CET i2p session made, we are mhstzljs4co2jpwexj73jdidkv6x7as43obxtxxiw445zg4yppka.b32.i2p
    [NFO] 2017-03-03 17:42:22.122867911 +0100 CET swarm obtained network address: aLsdUwe8LQYzJNJpio[..]rlB-4H8VAAAA
    [NFO] 2017-03-03 17:42:22.122957029 +0100 CET i2pupdate-0.9.29.su3 running

Downloaded the same i2pupdate-0.9.29.su3 with standalone i2psnark and comparing the two gives:

    # cmp i2pupdate-0.9.29.su3 ~/source/go/XD/storage/downloads/i2pupdate-0.9.29.su3 -b
    i2pupdate-0.9.29.su3 ~/source/go/XD/storage/downloads/i2pupdate-0.9.29.su3 differs: byte 4456451, row 18372 is  10 ^H   0 ^@

All in all, almost the same.. :)

[xd-log-finished.txt](https://github.com/majestrate/XD/files/817339/xd-log-finished.txt)

**Comment by majestrate** [comment]
i think that single file torrents should work now
multi file torrents probably not

**Comment by majestrate** [comment]
single file torrents working confirmed

**Comment by majestrate** [comment]
should be fixed now
