### ISSUE TITLE
Cant add torrents by local file path on windows

### ISSUE THREAD

**Issue by PotatoSUS** [majestrate/XD#104]
## info

160f2917fa85916046c997eccb5858a2e38c592e

OS: Windows

Architecture: X64

## problem

When i try to add a torrent by local file path on windows i get the follow error "failed to fetch torrent"

## backtrace / error messages
"
[NFO] 2023-11-05 21:28:21.0454784 -0300 -03 m=+15.516645601     fetching torrent from c:\Users\re\Downloads\rodrigo.torrent
[ERR] 2023-11-05 21:28:21.0462283 -0300 -03 m=+15.517395501     failed to fetch torrent: Get "c:\\Users\\re\\Downloads\\rodrigo.torrent": unsupported protocol scheme "c"

**Comment by r4sas** [comment]
Just not supported.

https://github.com/majestrate/XD/blob/160f2917fa85916046c997eccb5858a2e38c592e/lib/bittorrent/swarm/swarm.go#L331-L332

**Comment by majestrate** [comment]
would `file://c:/whatever/goes/here` work?

**Comment by r4sas** [comment]
> would `file://c:/whatever/goes/here` work?

nope

**Comment by majestrate** [comment]
try https://github.com/majestrate/XD/commit/baa5f672a964cc8cce6370bdc796179a90e3ba24

**Comment by r4sas** [comment]
> try [baa5f67](https://github.com/majestrate/XD/commit/baa5f672a964cc8cce6370bdc796179a90e3ba24)

`lib\util\helpers_windows.go:7:2: package os/path is not in std (D:\devel\go1.21.4.windows-amd64\go\src\os\path)`
