### ISSUE TITLE
unable to use on my win 10 home 64 pc desk

### ISSUE THREAD

**Issue by p060477** [majestrate/XD#105]
## info

git revision / version: [git revision or version here]

OS: [os here] win 10

Architecture: [architecture here] 64 bit

## problem unable to connect...

[insert description of problem here]

## backtrace / error messages

Error messages: [yes/no]

[insert any error messages here]

Backtrace: [yes/no]

[insert any backtraces here]

here it is the dos with all errors..:

[NFO] 2023-11-07 17:30:31.9585482 +0100 CET m=+0.006370001      starting XD-0.4.4
[NFO] 2023-11-07 17:30:32.0434505 +0100 CET m=+0.091272301      loaded config torrents.ini
[NFO] 2023-11-07 17:30:32.0434505 +0100 CET m=+0.091272301      Ensure filesystem storage
[NFO] 2023-11-07 17:30:32.0446972 +0100 CET m=+0.092519001      Swarm netLoop starting
[NFO] 2023-11-07 17:30:32.0456451 +0100 CET m=+0.093466901      RPC enabled
[NFO] 2023-11-07 17:30:32.0484643 +0100 CET m=+0.096286101      create new i2p session with 127.0.0.1:7656
[NFO] 2023-11-07 17:30:32.0489828 +0100 CET m=+0.096804601      opening i2p session
[NFO] 2023-11-07 17:30:34.0887827 +0100 CET m=+2.136604501      create new i2p session with 127.0.0.1:7656
[ERR] 2023-11-07 17:30:34.0914525 +0100 CET m=+2.139274301      failed to create i2p session: dial tcp 127.0.0.1:7656: connectex: No connection could be made because the target machine actively refused it.
[NFO] 2023-11-07 17:30:35.0970792 +0100 CET m=+3.144901001      opening i2p session
[NFO] 2023-11-07 17:30:37.1579794 +0100 CET m=+5.205801201      create new i2p session with 127.0.0.1:7656
[ERR] 2023-11-07 17:30:37.1591136 +0100 CET m=+5.206935401      failed to create i2p session: dial tcp 127.0.0.1:7656: connectex: No connection could be made because the target machine actively refused it.
[NFO] 2023-11-07 17:30:38.161834 +0100 CET m=+6.209655801       opening i2p session
[NFO] 2023-11-07 17:30:40.2078043 +0100 CET m=+8.255626101      create new i2p session with 127.0.0.1:7656
[ERR] 2023-11-07 17:30:40.208891 +0100 CET m=+8.256712801       failed to create i2p session: dial tcp 127.0.0.1:7656: connectex: No connection could be made because the target machine actively refused it.
[NFO] 2023-11-07 17:30:41.2185642 +0100 CET m=+9.266386001      opening i2p session
[NFO] 2023-11-07 17:30:43.2656067 +0100 CET m=+11.313428501     create new i2p session with 127.0.0.1:7656
[ERR] 2023-11-07 17:30:43.2662758 +0100 CET m=+11.314097601     failed to create i2p session: dial tcp 127.0.0.1:7656: connectex: No connection could be made because the target machine actively refused it.

how to solve...??
thxs so much in adv
cheers

**Comment by p060477** [comment]
hi, i missed i2p...now i have i2p on my pc so the situation is slightly changed:

[NFO] 2023-11-07 18:51:40.2857271 +0100 CET m=+0.007636701      starting XD-0.4.4
[NFO] 2023-11-07 18:51:40.4524276 +0100 CET m=+0.174337201      loaded config torrents.ini
[NFO] 2023-11-07 18:51:40.4524276 +0100 CET m=+0.174337201      Ensure filesystem storage
[NFO] 2023-11-07 18:51:40.4534556 +0100 CET m=+0.175365201      Swarm netLoop starting
[NFO] 2023-11-07 18:51:40.4539744 +0100 CET m=+0.175884001      RPC enabled
[NFO] 2023-11-07 18:51:40.4561396 +0100 CET m=+0.178049201      create new i2p session with 127.0.0.1:7656
[NFO] 2023-11-07 18:51:40.4561779 +0100 CET m=+0.178087501      opening i2p session
[NFO] 2023-11-07 18:52:00.4932859 +0100 CET m=+20.215195501     i2p session made, we are 4bpavzvwaennn4yqbtpkrtzt2qpgkjwdjsz7jdz5qq3h77xhwq6q.b32.i2p
[NFO] 2023-11-07 18:52:00.494335 +0100 CET m=+20.216244601      Generated new peer id: -XD0440-%7C%A6+%40%E58%B3%CCB%E0%ACt
[NFO] 2023-11-07 18:52:00.5957238 +0100 CET m=+20.317633401     Network context obtained
[NFO] 2023-11-07 18:52:00.5957238 +0100 CET m=+20.317633401     Swarm got network context

but now...??...if i put in the web add bar of my browser the :
http://127.0.0.1:7656/
or 
http://127.0.0.1:1488/ 

nothing happens...
why...??
thxs in adv
cheers
cheers

**Comment by p060477** [comment]
i'm still here...:
`[NFO] 2023-11-08 17:20:52.2585066 +0100 CET m=+0.004055801      starting XD-0.4.4
[NFO] 2023-11-08 17:20:52.366755 +0100 CET m=+0.112304201       loaded config torrents.ini
[NFO] 2023-11-08 17:20:52.3673089 +0100 CET m=+0.112858101      Ensure filesystem storage
[NFO] 2023-11-08 17:20:52.367841 +0100 CET m=+0.113390201       Swarm netLoop starting
[NFO] 2023-11-08 17:20:52.3688772 +0100 CET m=+0.114426401      RPC enabled
[NFO] 2023-11-08 17:20:52.3718096 +0100 CET m=+0.117358801      create new i2p session with 127.0.0.1:7656
[NFO] 2023-11-08 17:20:52.3805983 +0100 CET m=+0.126147501      opening i2p session
[NFO] 2023-11-08 17:20:58.4038665 +0100 CET m=+6.149415701      i2p session made, we are 46twomalnuyvl5aqyf4d4bwjk4rxcufvjwckwpblxtpyogm4xcxq.b32.i2p
[NFO] 2023-11-08 17:20:58.4048983 +0100 CET m=+6.150447501      Generated new peer id: -XD0440-I%18%FF%DC%0F%D5%98%9B%8BX%FDE
[NFO] 2023-11-08 17:20:58.4331792 +0100 CET m=+6.178728401      Network context obtained
[NFO] 2023-11-08 17:20:58.4331792 +0100 CET m=+6.178728401      Swarm got network context`

**Comment by majestrate** [comment]
use `http://127.0.0.1:1776`

**Comment by p060477** [comment]
hi, first thxs, now the webui starts!...how do you find the exact 1776 instead of other 7656 indicated...??
anyway no able to dl anything...see some examplaes:

`[NFO] 2023-11-08 20:06:39.5367011 +0100 CET m=+251.387715701    fetching torrent from http://www.1337x.to/torrent/3225002/Bob-Dylan-1962-The-Freewheelin-Bob-Dylan-Outtakes-STU-FLAC/
[ERR] 2023-11-08 20:06:39.5382494 +0100 CET m=+251.389264001    failed to fetch torrent: Get "http://www.1337x.to/torrent/3225002/Bob-Dylan-1962-The-Freewheelin-Bob-Dylan-Outtakes-STU-FLAC/": NAMING REPLY RESULT=INVALID_KEY NAME=www.1337x.to

[NFO] 2023-11-08 20:06:44.740648 +0100 CET m=+256.591662601     fetching torrent from http://www.1337x.to/torrent/3225002/Bob-Dylan-1962-The-Freewheelin-Bob-Dylan-Outtakes-STU-FLAC/
[ERR] 2023-11-08 20:06:44.7413954 +0100 CET m=+256.592410001    failed to fetch torrent: Get "http://www.1337x.to/torrent/3225002/Bob-Dylan-1962-The-Freewheelin-Bob-Dylan-Outtakes-STU-FLAC/": NAMING REPLY RESULT=INVALID_KEY NAME=www.1337x.to

[NFO] 2023-11-08 20:08:11.4893537 +0100 CET m=+343.340368301    fetching torrent from https://glodls.to/down.php?id=12102126&name=Bob%20Dylan%20-%20Shadow%20Kingdom%20%282023%20Rock%29%20%5BFlac%2024-96%5D.torrent
[ERR] 2023-11-08 20:08:11.4902172 +0100 CET m=+343.341231801    failed to fetch torrent: Get "https://glodls.to/down.php?id=12102126&name=Bob%20Dylan%20-%20Shadow%20Kingdom%20%282023%20Rock%29%20%5BFlac%2024-96%5D.torrent": NAMING REPLY RESULT=INVALID_KEY NAME=glodls.to

[NFO] 2023-11-08 20:09:43.9239649 +0100 CET m=+435.774979501    fetching torrent from https://torrentdownloads.me/torrent/1704426234/Bob-Dylan-And-The-Rolling-Thunder-Revue---New-Orleans-1976-Soundboard-%282023%29-FLAC-PMEDIA%5D-%E2%AD%90%EF%B8%8F
[ERR] 2023-11-08 20:09:43.9247405 +0100 CET m=+435.775755101    failed to fetch torrent: Get "https://torrentdownloads.me/torrent/1704426234/Bob-Dylan-And-The-Rolling-Thunder-Revue---New-Orleans-1976-Soundboard-%282023%29-FLAC-PMEDIA%5D-%E2%AD%90%EF%B8%8F": NAMING REPLY RESULT=INVALID_KEY NAME=torrentdownloads.me

why...??
thxs in adv for yr kind attn
`

**Comment by p060477** [comment]
this is the last proof with a simple torrent file...:

![Immagine](https://github.com/majestrate/XD/assets/12773559/5f242305-84d6-4d66-8626-daf27e8585cc)



see...:

`[NFO] 2023-11-08 20:27:17.9090155 +0100 CET m=+1489.760030101   fetching torrent from https://glodls.to/lass=%27ttable_col1%27%20align=%27center%27%3E%3Ca%20href=%20http:/itorrents.org/torrent/AB1F7B2AF22AF9BC19256D6F7026B1BFCECE389A.torrent&name=LibreOffice%204%202%203%20Win%20x86
[ERR] 2023-11-08 20:27:17.9115396 +0100 CET m=+1489.762554201   failed to fetch torrent: Get "https://glodls.to/lass=%27ttable_col1%27%20align=%27center%27%3E%3Ca%20href=%20http:/itorrents.org/torrent/AB1F7B2AF22AF9BC19256D6F7026B1BFCECE389A.torrent&name=LibreOffice%204%202%203%20Win%20x86": NAMING REPLY RESULT=INVALID_KEY NAME=glodls.to`


any ideas?

**Comment by p060477** [comment]
instead if i past a magnet link url i got:

`[NFO] 2023-11-08 21:49:13.0679433 +0100 CET m=+6404.918957901   announcing to http://s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p:80/a
[WRN] 2023-11-08 21:49:27.5455905 +0100 CET m=+6419.396605101   http://s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p:80/a got error while announcing: Get "http://s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p:80/a?compact=1&downloaded=0&info_hash=%B7%21dTv%BC%E7%8B%5C%C0Y%F3%60%3F%E7i%FE%26%E6i&ip=U4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSpgNSnhmCBMKyY0XzQ1zOu-Yxu2UKf3y3egnXZTf-J5bmBQAEAAcAAA%3D%3D.i2p&left=0&numwant=10&peer_id=-XD0440-%B8q%9A%07%CBn%86%2F%18%17c%81&port=6881&uploaded=0": NAMING REPLY RESULT=INVALID_KEY NAME=s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p

[WRN] 2023-11-08 21:49:27.5575561 +0100 CET m=+6419.408570701   announce to http://s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p/a failed: Get "http://s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p:80/a?compact=1&downloaded=0&info_hash=%B7%21dTv%BC%E7%8B%5C%C0Y%F3%60%3F%E7i%FE%26%E6i&ip=U4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSpgNSnhmCBMKyY0XzQ1zOu-Yxu2UKf3y3egnXZTf-J5bmBQAEAAcAAA%3D%3D.i2p&left=0&numwant=10&peer_id=-XD0440-%B8q%9A%07%CBn%86%2F%18%17c%81&port=6881&uploaded=0": NAMING REPLY RESULT=INVALID_KEY NAME=s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p

[WRN] 2023-11-08 21:50:16.2717045 +0100 CET m=+6468.122719101   http://by7luzwhx733fhc5ug2o75dcaunblq2ztlshzd7qvptaoa73nqua.b32.i2p:80/a got error while announcing: Get "http://by7luzwhx733fhc5ug2o75dcaunblq2ztlshzd7qvptaoa73nqua.b32.i2p:80/a?compact=1&downloaded=0&info_hash=%15n%3DY%0C%3E%F7Aq%0DM%93%D6%C3%3Ej%17B%BD%BA&ip=U4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSpgNSnhmCBMKyY0XzQ1zOu-Yxu2UKf3y3egnXZTf-J5bmBQAEAAcAAA%3D%3D.i2p&left=0&numwant=10&peer_id=-XD0440-%B8q%9A%07%CBn%86%2F%18%17c%81&port=6881&uploaded=0": EOF
[WRN] 2023-11-08 21:50:16.2802105 +0100 CET m=+6468.131225101   announce to http://by7luzwhx733fhc5ug2o75dcaunblq2ztlshzd7qvptaoa73nqua.b32.i2p/a failed: Get "http://by7luzwhx733fhc5ug2o75dcaunblq2ztlshzd7qvptaoa73nqua.b32.i2p:80/a?compact=1&downloaded=0&info_hash=%15n%3DY%0C%3E%F7Aq%0DM%93%D6%C3%3Ej%17B%BD%BA&ip=U4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSpgNSnhmCBMKyY0XzQ1zOu-Yxu2UKf3y3egnXZTf-J5bmBQAEAAcAAA%3D%3D.i2p&left=0&numwant=10&peer_id=-XD0440-%B8q%9A%07%CBn%86%2F%18%17c%81&port=6881&uploaded=0": EOF
[NFO] 2023-11-08 21:50:16.290283 +0100 CET m=+6468.141297601    announcing to http://swhb5i7wcjcohmus3gbt3w6du6pmvl3isdvxvepuhdxxkfbzao6q.b32.i2p:80/a
[WRN] 2023-11-08 21:50:29.8862558 +0100 CET m=+6481.737270401   http://swhb5i7wcjcohmus3gbt3w6du6pmvl3isdvxvepuhdxxkfbzao6q.b32.i2p:80/a got error while announcing: Get "http://swhb5i7wcjcohmus3gbt3w6du6pmvl3isdvxvepuhdxxkfbzao6q.b32.i2p:80/a?compact=1&downloaded=0&info_hash=%15n%3DY%0C%3E%F7Aq%0DM%93%D6%C3%3Ej%17B%BD%BA&ip=U4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSpgNSnhmCBMKyY0XzQ1zOu-Yxu2UKf3y3egnXZTf-J5bmBQAEAAcAAA%3D%3D.i2p&left=0&numwant=10&peer_id=-XD0440-%B8q%9A%07%CBn%86%2F%18%17c%81&port=6881&uploaded=0": NAMING REPLY RESULT=INVALID_KEY NAME=swhb5i7wcjcohmus3gbt3w6du6pmvl3isdvxvepuhdxxkfbzao6q.b32.i2p

[WRN] 2023-11-08 21:50:29.895652 +0100 CET m=+6481.746666601    announce to http://swhb5i7wcjcohmus3gbt3w6du6pmvl3isdvxvepuhdxxkfbzao6q.b32.i2p/a failed: Get "http://swhb5i7wcjcohmus3gbt3w6du6pmvl3isdvxvepuhdxxkfbzao6q.b32.i2p:80/a?compact=1&downloaded=0&info_hash=%15n%3DY%0C%3E%F7Aq%0DM%93%D6%C3%3Ej%17B%BD%BA&ip=U4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSpgNSnhmCBMKyY0XzQ1zOu-Yxu2UKf3y3egnXZTf-J5bmBQAEAAcAAA%3D%3D.i2p&left=0&numwant=10&peer_id=-XD0440-%B8q%9A%07%CBn%86%2F%18%17c%81&port=6881&uploaded=0": NAMING REPLY RESULT=INVALID_KEY NAME=swhb5i7wcjcohmus3gbt3w6du6pmvl3isdvxvepuhdxxkfbzao6q.b32.i2p

[NFO] 2023-11-08 21:50:29.9051691 +0100 CET m=+6481.756183701   announcing to http://punzipidirfqspstvzpj6gb4tkuykqp6quurj6e23bgxcxhdoe7q.b32.i2p:80/a
[NFO] 2023-11-08 21:50:34.3153351 +0100 CET m=+6486.166349701   http://punzipidirfqspstvzpj6gb4tkuykqp6quurj6e23bgxcxhdoe7q.b32.i2p:80/a got 0 peers for 156e3d590c3ef741710d4d93d6c33e6a1742bdba
[NFO] 2023-11-08 21:50:34.3158611 +0100 CET m=+6486.166875701   announcing to http://s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p:80/a
[WRN] 2023-11-08 21:50:43.324463 +0100 CET m=+6495.175477601    http://s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p:80/a got error while announcing: Get "http://s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p:80/a?compact=1&downloaded=0&info_hash=%15n%3DY%0C%3E%F7Aq%0DM%93%D6%C3%3Ej%17B%BD%BA&ip=U4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSpgNSnhmCBMKyY0XzQ1zOu-Yxu2UKf3y3egnXZTf-J5bmBQAEAAcAAA%3D%3D.i2p&left=0&numwant=10&peer_id=-XD0440-%B8q%9A%07%CBn%86%2F%18%17c%81&port=6881&uploaded=0": NAMING REPLY RESULT=INVALID_KEY NAME=s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p

[WRN] 2023-11-08 21:50:43.3341805 +0100 CET m=+6495.185195101   announce to http://s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p/a failed: Get "http://s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p:80/a?compact=1&downloaded=0&info_hash=%15n%3DY%0C%3E%F7Aq%0DM%93%D6%C3%3Ej%17B%BD%BA&ip=U4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSplOAxnuUCPGq7dmmLoOLRpaCjw17KuahibAq~YnZkxKmU4DGe5QI8art2aYug4tGloKPDXsq5qGJsCr9idmTEqZTgMZ7lAjxqu3Zpi6Di0aWgo8NeyrmoYmwKv2J2ZMSpgNSnhmCBMKyY0XzQ1zOu-Yxu2UKf3y3egnXZTf-J5bmBQAEAAcAAA%3D%3D.i2p&left=0&numwant=10&peer_id=-XD0440-%B8q%9A%07%CBn%86%2F%18%17c%81&port=6881&uploaded=0": NAMING REPLY RESULT=INVALID_KEY NAME=s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p`


is there  way to finally be able to use your XD on windows 10....???

**Comment by r4sas** [comment]
XD is supports ONLY I2P torrents and magnets. There is NO clearnet support, and it will never be added.

**Comment by p060477** [comment]
and where we are able to find:
**ONLY I2P torrents and magnets.**

and how to find the exact webui add.:
http://127.0.0.1:1776
where is it written clearly...??
in yr guide page there is :
http://127.0.0.1:1488/
and in the sw dos window pop up it is clearly written:
http://127.0.0.1:7656/

where a normal siple person should be able to imagine the:
http://127.0.0.1:1776
...???...
thxs os much in adv
cheers

**Comment by majestrate** [comment]
> and where we are able to find: **ONLY I2P torrents and magnets.**
> 
> and how to find the exact webui add.: http://127.0.0.1:1776 where is it written clearly...?? in yr guide page there is : http://127.0.0.1:1488/ 

which guide page is this listed in, that page needs to be updated.

and in the sw dos window pop up it is clearly written: http://127.0.0.1:7656/
> 
> where a normal simple guy should be able **to imagine** the: http://127.0.0.1:1776 ...???... thxs os much in adv cheers

**Comment by p060477** [comment]
1)
and where we are able to find:
ONLY I2P torrents and magnets.

2)
why you do not update yr guide web page...how a poor person should be able to imagine a different webui address....??... :(

**Comment by majestrate** [comment]
docs for webui URL have been updated. took a while to remember where they are. i have not worked on this in ages.
https://github.com/xd-torrent/xd-docs/commit/abd5f6fd1a1995ac54634708b1b186af294c4177

**Comment by p060477** [comment]
thxs so now the MORE important thing:
where we are able to find:
ONLY I2P torrents and magnets urls....
cause if i put normal torrent or magnet yr sw do not accept them as per r4sas stating:
"XD is supports ONLY I2P torrents and magnets. There is NO clearnet support, and it will never be added."...

so the much important answer you have to give is this:
WHERE we are able to find **ONLY I2P torrents and magnets.**

**Comment by majestrate** [comment]
>WHERE we are able to find ONLY I2P torrents and magnets.

I dont know, i have not used i2p in a long time. someone else may know.

**Comment by p060477** [comment]
but without them yr sw **does not work at all**.....so you create a sw and do not know how to make it working...??

**Comment by majestrate** [comment]
i haven't worked on this codebase about 5 years. it would be a good idea to rewrite it right about now with a better UX in mind.

**Comment by p060477** [comment]
it is a real pity for a sw that claims to be able to beat the vpn in privacy that is not workin at all... 
a very big pity :(

**Comment by p060477** [comment]
it is a real pity for a sw that claims to be able to beat the vpn in privacy that is not workin at all...
a very big pity :(

**Comment by majestrate** [comment]
it hasn't been properly updated in 5 years my guy.
i'll see if i can swing back around and give it a bit of love, looks like interest in i2p torrents are continuing to rise. i would've never gotten this kind of bug report back then, the end user demographic was tiny compared to now.

**Comment by p060477** [comment]
hi, first thxs for yr attn 
but have you seen this BUG...??...:
https://github.com/majestrate/XD/issues/110

**Comment by majestrate** [comment]
documentation pages about web ui were updated. closing as fixed.
