### ISSUE TITLE
unable to find i2p torrent url and magnets...

### ISSUE THREAD

**Issue by p060477** [majestrate/XD#106]
## info

git revision / version: [git revision or version here]

OS: [os here] win 10

Architecture: [architecture here] 64

## problem yr tool is not working...

[insert description of problem here]

where we are able to find:
ONLY I2P torrents and magnets....
**without yr tool is simply unuseless at all...**

## backtrace / error messages

Error messages: [yes/no]

[insert any error messages here]

Backtrace: [yes/no]

[insert any backtraces here]

**Comment by majestrate** [comment]
XD is an i2p only BitTorrent client.
If you want to use BitTorrent outside of i2p you'll want to use a BitTorrent client that does not only work inside I2P.

**Comment by p060477** [comment]
i want to use yr xd torrent sw...so how to be able to download something...??...you sate that only I2P torrents and magnets urls works so WHERE to be able to find them in order to put the url in the webui and finally be abkle to see if yr sw works...??

**Comment by r4sas** [comment]
http://tracker2.postman.i2p/

**Comment by p060477** [comment]
also yr i2p tracker lead to this frustrating error:
[WRN] 2023-11-12 21:32:23.9228185 +0100 CET m=+332.326041801    announce to http://swhb5i7wcjcohmus3gbt3w6du6pmvl3isdvxvepuhdxxkfbzao6q.b32.i2p/a failed: Get "http://swhb5i7wcjcohmus3gbt3w6du6pmvl3isdvxvepuhdxxkfbzao6q.b32.i2p:80/a?compact=1&downloaded=0&info_hash=%D5%E0%AC%A9%1Cb%F2%F2%CE0%C3%00%1B%D2%E8%8D%98%27j%FD&ip=CvJoeH3vWi0sjDc07L14CPEiMlLDsKXHbAncIcnhy7VIN17cbWjL3JN85i1HRbVR1FrTjvPFNh1JBMjwgAzs~X1ovcjky8lVAtYb1RlQ6dl60mBfmht~ailLcXrvqp3~kYOZLHdb3-88OT7bnFGimVN3XoMasX5Y5X7xeVfy2o9kMBqT-hW682WcWIQhrTGJJyksDBO33MATeOCXHbKMq0Zz5FxkuTdJiVTZWpetZ36QrAqy~LI0z~EmREvOBjBDC49PQ25PM7t0IY5GK7aBRFeShxhFzzg9eYlktrU0e~qAzBFPIP4sxXlfYQcRRauLhC1ddyB7KF47-DdqqpNQdEsFajjkOK~4uw-Kiq15yOe9y8EWmwZHHMff8h0g79Wd9izLv0GPD6F0OkI501sEDogjncj7RvE0d-CuohlNxUe3q~KTBtt3NMMqCybRk71UgaJsAoCxYtgKLbwoNGqvwX0hm~ONW-JjaE70XBu1dQSV30xJov-rZqvqEBj9fvRnBQAEAAcAAA%3D%3D.i2p&left=320498430&numwant=10&peer_id=-XD0440-%E7%E6%0D%DAR%92%E4%DC_%A6%04%0D&port=6881&uploaded=0": NAMING REPLY RESULT=INVALID_KEY NAME=swhb5i7wcjcohmus3gbt3w6du6pmvl3isdvxvepuhdxxkfbzao6q.b32.i2p


why...??...this is  a I2P torrent and magnet urls dl from the site you give:
http://tracker2.postman.i2p/

so where is the BUG...???

**Comment by p060477** [comment]
Hi, there is no way to put a torrent url in yr webui...it only accepts magnets urls...why...??
is it a bug...?...if yes should i have to open an issue...??
