### ISSUE TITLE
i want to use **yr xd torrent sw**

### ISSUE THREAD

**Issue by p060477** [majestrate/XD#107]
i want to use **yr xd torrent sw**...so :
**how to be able to download something...??**...you state that only I2P torrents and magnets urls works so:
WHERE to be able to find them in order to put the url in the webui and finally be able to see if yr sw works...??

_Originally posted by @p060477 in https://github.com/majestrate/XD/issues/106#issuecomment-1806929976_

**Comment by r4sas** [comment]
Stop breaking new issues.

**Comment by p060477** [comment]
i was **forced by you**...cause you closed a **no answered one....**

**Comment by majestrate** [comment]
please try to minimize the number of open issues you make. thanks.
if you have something that isn't strictly a software bug like QA or ambiguity please use the discussions area of the github: #108

**Comment by p060477** [comment]
Hi, there is no way to put a torrent url in yr webui...it only accepts magnets urls...why...??
is it a bug...?...if yes should i have to open an issue...??
