### ISSUE TITLE
Logo needed

### ISSUE THREAD

**Issue by majestrate** [majestrate/XD#11]
self explanatory.

**Comment by l-n-s** [comment]
![xd_logo](https://user-images.githubusercontent.com/13422305/29044628-d5c44868-7baf-11e7-9f63-c6606cdb909b.png)
mad gimp skills

**Comment by majestrate** [comment]
i liek

**Comment by majestrate** [comment]
can I have a smaller version as well?

**Comment by l-n-s** [comment]
[logo.zip](https://github.com/majestrate/XD/files/1208084/logo.zip)
sure

**Comment by majestrate** [comment]
added in https://github.com/majestrate/XD/commit/b9df5a09fb086dc58cc6a26ef4bc59162023ad5a
