### ISSUE TITLE
Configure options by using environment variables

### ISSUE THREAD

**Issue by l-n-s** [majestrate/XD#14]
IMO it could be useful to have config dir option: where to find config, keys and all stuff.

    /usr/local/bin/XD --config-dir /home/user/.XD

and read from environment:

    export XD_HOME='/home/user/.XD'
    ./XD

That way it  could be more flexible.

**Comment by majestrate** [comment]
right now you specify the config as an argument

i.e. `./XD /path/to/config.ini`

**Comment by l-n-s** [comment]
Yes, but wouldn't it be easier to have all "system" files in one folder, configurable in one parameter? For system daemons and containers, not to mess with config file...

**Comment by majestrate** [comment]
hmmmm maybe

**Comment by majestrate** [comment]
I like the `XD_HOME=whatever` aproach better personally.

**Comment by majestrate** [comment]
what about using chroot?

**Comment by l-n-s** [comment]
Also, pls expose environment variable XD_I2P_ADDRESS to configure SAM

**Comment by majestrate** [comment]
so you want `XD_HOME` and `XD_I2P_ADDRESS` ?

**Comment by l-n-s** [comment]
yes, please :)

> what about using chroot?
I miss context?

**Comment by majestrate** [comment]
can't chroot be done by init scripts?

**Comment by majestrate** [comment]
added initial in https://github.com/majestrate/XD/commit/f37c934f31aac20cbf43aae98ac1dbf02634c367
