### ISSUE TITLE
[testnet] downloaded file hash missmatch

### ISSUE THREAD

**Issue by l-n-s** [majestrate/XD#19]
```
[user@n1 XD_test]$ docker exec -it xd1 sha1sum storage/downloads/testfile.iso
d5db28c3951427f9bf701d99a0035427459c74b3  storage/downloads/testfile.iso
[user@n1 XD_test]$ docker exec -it xd2 sha1sum storage/downloads/testfile.iso
8c206a1a87599f532ce68675536f0b1546900d7a  storage/downloads/testfile.iso
```

Full logs of seeder and leecher are in archive.

[logs.zip](https://github.com/majestrate/XD/files/1225021/logs.zip)

**Comment by majestrate** [comment]
there are no pieces exchanged

**Comment by l-n-s** [comment]
still doesn't download
[logs.zip](https://github.com/majestrate/XD/files/1228321/logs.zip)

**Comment by majestrate** [comment]
try https://github.com/majestrate/XD/commit/c0470a598b7ec8149a55b5ea9fe1bbc97aa01bc4

**Comment by l-n-s** [comment]
[logs.zip](https://github.com/majestrate/XD/files/1228572/logs.zip)

**Comment by majestrate** [comment]
seeder and leecher logs are backwards
seeder is leecher and leecher is seeder

**Comment by l-n-s** [comment]
kk. let me know when to run tests again

**Comment by majestrate** [comment]
try again

**Comment by l-n-s** [comment]
Still no luck. Logs:

[seeder](https://gist.github.com/l-n-s/17df81cd62d9cbc954b8b4ef30aa4e7e/raw/16572ebfc02ea3ffa2edd65a799f598e91a2bba6/seeder.txt)

[leecher](https://gist.github.com/l-n-s/17df81cd62d9cbc954b8b4ef30aa4e7e/raw/16572ebfc02ea3ffa2edd65a799f598e91a2bba6/leecher.txt)

**Comment by l-n-s** [comment]
Works correct now

**Comment by majestrate** [comment]
:+D
