### ISSUE TITLE
XD-0.0.9-pre-1-linux-amd64 - downloading 40kbyte/sec, no pieces

### ISSUE THREAD

**Issue by mathiasfriman** [majestrate/XD#21]
Hi,

wonder if it's just me or if anybody else has this problem with the XD 0.0.9 pre 1 build. I selected a torrent which has a lot of peers as usual, and there's a lot of traffic, XD webui reports ~40kbyte/sec, the i2pd node is up to 200 kbyte/sec, but after three hours, the progress on one of the same torrent is still 0.03%.

**Restarting XD makes it download some pieces again**, and then stop. Something's borked?

    [NFO] 2017-09-15 11:58:26.36455999 +0200 CEST m=+0.026784130	starting XD-0.0.8-2bd94c3
    [NFO] 2017-09-15 11:58:26.365883218 +0200 CEST m=+0.028107356	loaded config torrents.ini
    [NFO] 2017-09-15 11:58:26.365898041 +0200 CEST m=+0.028122162	Ensure filesystem storage
    [NFO] 2017-09-15 11:58:26.367207465 +0200 CEST m=+0.029431614	generated peer id -XD0080-t%9D%DFN%81%A1%0F%94%D0%FBKT
    [NFO] 2017-09-15 11:58:26.368732518 +0200 CEST m=+0.030956767	RPC enabled
    [NFO] 2017-09-15 11:58:26.368768624 +0200 CEST m=+0.030992808	create new i2p session with 127.0.0.1:7656
    [NFO] 2017-09-15 11:58:26.369500725 +0200 CEST m=+0.031724919	opening i2p session
    [NFO] 2017-09-15 11:58:46.393584316 +0200 CEST m=+20.055808436	i2p session made, we are xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.b32.i2p
    [NFO] 2017-09-15 11:58:46.395935072 +0200 CEST m=+20.058159222	Global Speed: Upload: 0.00B/sec Download: 0.00B/sec
    [NFO] 2017-09-15 11:58:47.37337346 +0200 CEST m=+21.035597634	xxx-torrent running
    [NFO] 2017-09-15 11:58:47.373407678 +0200 CEST m=+21.035631872	i2pupdate-0.9.31.su3 running
    [NFO] 2017-09-15 11:58:56.396635709 +0200 CEST m=+30.058859910	Global Speed: Upload: 0.00B/sec Download: 0.00B/sec
    [NFO] 2017-09-15 11:59:06.397314041 +0200 CEST m=+40.059538238	Global Speed: Upload: 0.00B/sec Download: 0.00B/sec
    [NFO] 2017-09-15 11:59:16.398077119 +0200 CEST m=+50.060301326	Global Speed: Upload: 0.00B/sec Download: 0.00B/sec
    [NFO] 2017-09-15 11:59:26.398780156 +0200 CEST m=+60.061004368	Global Speed: Upload: 0.00B/sec Download: 0.00B/sec
    [NFO] 2017-09-15 11:59:36.39937598 +0200 CEST m=+70.061600158	Global Speed: Upload: 0.00B/sec Download: 0.00B/sec
    [NFO] 2017-09-15 11:59:46.400049866 +0200 CEST m=+80.062274131	Global Speed: Upload: 0.00B/sec Download: 0.00B/sec
    [NFO] 2017-09-15 11:59:47.373759024 +0200 CEST m=+81.035983144	announcing to 
    [NFO] 2017-09-15 11:59:47.373750946 +0200 CEST m=+81.035975056	announcing to 
    [NFO] 2017-09-15 11:59:56.400810576 +0200 CEST m=+90.063034777	Global Speed: Upload: 0.00B/sec Download: 0.00B/sec
    [NFO] 2017-09-15 12:00:06.401471469 +0200 CEST m=+100.063695590	Global Speed: Upload: 0.00B/sec Download: 0.00B/sec
    [NFO] 2017-09-15 12:00:16.402154537 +0200 CEST m=+110.064378722	Global Speed: Upload: 0.00B/sec Download: 0.00B/sec
    [WRN] 2017-09-15 12:00:23.41277912 +0200 CEST m=+117.075003299	failed to resolve peer NAMING REPLY RESULT=INVALID_KEY NAME=7tcc77edmwl4apdaaplgyh3do6jrcqcjcd5vl2hd5lbeswfqkrtq.b32.i2p

    [NFO] 2017-09-15 12:00:26.402807093 +0200 CEST m=+120.065031256	Global Speed: Upload: 0.00B/sec Download: 11.21KB/sec
    [NFO] 2017-09-15 12:00:36.403683871 +0200 CEST m=+130.065908185	Global Speed: Upload: 0.00B/sec Download: 4.80KB/sec
    [NFO] 2017-09-15 12:00:46.2240353 +0200 CEST m=+139.886259524	xxx-torrent got piece 39
    [NFO] 2017-09-15 12:00:46.40419205 +0200 CEST m=+140.066416157	Global Speed: Upload: 0.00B/sec Download: 19.21KB/sec
    [NFO] 2017-09-15 12:00:48.023801638 +0200 CEST m=+141.686025784	i2pupdate-0.9.31.su3 got piece 33
    [NFO] 2017-09-15 12:00:56.404772335 +0200 CEST m=+150.066996445	Global Speed: Upload: 0.00B/sec Download: 35.22KB/sec
    [NFO] 2017-09-15 12:00:58.93085287 +0200 CEST m=+152.593077018	i2pupdate-0.9.31.su3 got piece 13
    [NFO] 2017-09-15 12:01:06.405460901 +0200 CEST m=+160.067685048	Global Speed: Upload: 0.00B/sec Download: 44.07KB/sec
    [NFO] 2017-09-15 12:01:16.406094021 +0200 CEST m=+170.068318162	Global Speed: Upload: 0.00B/sec Download: 72.95KB/sec
    [NFO] 2017-09-15 12:01:19.515193376 +0200 CEST m=+173.177417634	i2pupdate-0.9.31.su3 got piece 42
    [NFO] 2017-09-15 12:01:26.406660142 +0200 CEST m=+180.068884258	Global Speed: Upload: 0.00B/sec Download: 84.86KB/sec

**Comment by majestrate** [comment]
Yeah I noticed, next pre release of 0.0.9 will have that fixed. The piece eslection algorithm has been horrible up until recently.

**Comment by majestrate** [comment]
should be better in https://github.com/majestrate/XD/releases/tag/v0.0.9-pre-2

**Comment by mathiasfriman** [comment]
It indeed is :)
