### ISSUE TITLE
Idea: Upload torrent to anodex straight from XD

### ISSUE THREAD

**Issue by l-n-s** [majestrate/XD#28]
User chooses directory/file to share and adds metadata, gets back Anodex URI, ready to share with other users.

**Comment by majestrate** [comment]
would rather not tie XD to one index

**Comment by l-n-s** [comment]
Yes, I mean, if anodex instances will have common API for sharing torrent files, one could setup his own anodex and configure XD to use it. Sharing torrent files currently is pain, the less pain - the better!

**Comment by majestrate** [comment]
the api on anodex requires a login credential. but yeah it could work if there was more than 1 anodex.

**Comment by l-n-s** [comment]
probably a poor idea
