### ISSUE TITLE
API call ListTorrentDetailed

### ISSUE THREAD

**Issue by l-n-s** [majestrate/XD#30]
Need detailed torrent list, for displaying front page of webui. Right now API is getting spammed with n requests (for every torrent) each second, it may cause problems when n > 100.

**Comment by majestrate** [comment]
what about a ListManyTorrentInfos function?

**Comment by l-n-s** [comment]
IMO better to request all available torrent infos, and filter them by status. You suggest to request many torrent infos by providing their IDs?

**Comment by majestrate** [comment]
> You suggest to request many torrent infos by providing their IDs?
yes

**Comment by l-n-s** [comment]
We were discussing this lately, RPC command via POST ListTorrentDetailed (analogy of verbose ListTorrent command), returns detailed list of all known torrents.

**Comment by majestrate** [comment]
fixed in https://github.com/majestrate/XD/commit/6b9e38ffe30367a2f400ef8834bbca39835b6925
