### ISSUE TITLE
Latest git version "failed to fetch: invalid piece" on every torrent

### ISSUE THREAD

**Issue by mathiasfriman** [majestrate/XD#32]
Building my own XD from git (0253542) , I get

    [ERR] 2017-09-27 17:31:45.713735207 +0200 CEST	failed to fetch: invalid piece

on all torrents I try, even i2pupdate

EDIT: The files gets downloaded correctly, just not added to the queue. When starting an old version like 0.0.9-pre-2, the downloads is shown in the webgui and added for download.

**Comment by majestrate** [comment]
Must be a bad peer, right now the code does not ban peers that try to poison the swarm.

Will look into it.

**Comment by majestrate** [comment]
should be fixed in https://github.com/majestrate/XD/commit/261abfd1b71527124dd2a62af1de3fe26e218006
