### ISSUE TITLE
Count seeding ratio for torrents

### ISSUE THREAD

**Issue by l-n-s** [majestrate/XD#35]

**Comment by majestrate** [comment]
try https://github.com/majestrate/XD/commit/f80106e4b54fc2e70c2957ec71832cc11a26bde3 , has command line ratio tracking.

**Comment by majestrate** [comment]
rather, https://github.com/majestrate/XD/commit/e53ccb5a95414e7793abba660ce2ac864e7e2bdf

**Comment by l-n-s** [comment]
yep, it works
