### ISSUE TITLE
Create a webpage and documentation

### ISSUE THREAD

**Issue by l-n-s** [majestrate/XD#36]
Assign me :wink:

**Comment by l-n-s** [comment]
```
05:41 <i2pr> [Freenode/Richard_F] Hot news, XD compiles under OpenBSD current without having to patch the hell out of it.
05:43 <i2pr> [Freenode/Richard_F] Maybe its docs should be uptated to explain that a SAM bridge is required.
```

**Comment by l-n-s** [comment]
[XD_website.zip](https://github.com/majestrate/XD/files/1752672/XD_website.zip)

Created very basic web page. @majestrate fix opengraph tags if you like (site paths and stuff)

**Comment by majestrate** [comment]
What do I do with this?

**Comment by l-n-s** [comment]
What do you do with archive? Probably, publish content at i2p.rocks or I may create a github pages repo for it.  or do you mean opengraph tags?

**Comment by majestrate** [comment]
I'd rather keep i2p.rocks off this, let's do github pages repo.

**Comment by l-n-s** [comment]
https://xd-torrent.github.io/  done
