### ISSUE TITLE
Common default directories

### ISSUE THREAD

**Issue by l-n-s** [majestrate/XD#41]
Other torrent clients download files by default to ~/Downloads and store config files in ~/.config and misc files in ~/.local/share... sounds like a good idea to separate downloads and stuff to have on different locations...

May XD have this before 0.1?

**Comment by majestrate** [comment]
those are linux specific paths, not sure what freebsd uses but macos, windows and linux all would use
different paths.

by default i chose what i chose because it's portable across every platform, these values are just defaults
and they can be changed trivially.

**Comment by l-n-s** [comment]
Okay, XD seems to be like a torrent "daemon", so defaults will not matter -- everything should be configured for a system...

Can it be configured so that downloads will go in `/media/Downloads` and other files (torrents, etc) in `/var/lib/XD`?

**Comment by majestrate** [comment]
yes it can
