### ISSUE TITLE
crashing with "out of memory" when doing set-piece-window 128

### ISSUE THREAD

**Issue by l-n-s** [majestrate/XD#44]
[crash_log.zip](https://github.com/majestrate/XD/files/1679774/crash_log.zip)

testnet with master branch

**Comment by majestrate** [comment]
Out of memory is out of memory nothing can be done except reduce memory use or increase memory capacity.

**Comment by l-n-s** [comment]
OK, idk if you have seen the log, just thought maybe it's something different. There are no issues with memory when I use default piece-window.

**Comment by majestrate** [comment]
Rather, commit 8712d80

**Comment by l-n-s** [comment]
seems to be fixed
