### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mathiasfriman** [majestrate/XD#5]
From the latest commit 2cad16d . Same conditions as in #3 otherwise, same torrent.

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4d5131]

    goroutine 1021 [running]:
    panic(0x73eaa0, 0xc4200100f0)
              /usr/local/go/src/runtime/panic.go:500 +0x1a1
    xd/lib/bittorrent/swarm.(*PeerConn).runReader(0xc4200fb6b0)
              /home/mathias/source/go/XD/src/xd/lib/bittorrent/swarm/peer.go:215 +0x9d1
    created by xd/lib/bittorrent/swarm.(*PeerConn).start
              /home/mathias/source/go/XD/src/xd/lib/bittorrent/swarm/peer.go:68 +0x61

**Comment by majestrate** [comment]
i see the problem, think i fixed it in https://github.com/majestrate/XD/commit/6af021549b1b6fd0f4a122d42b8708611aa273fe

**Comment by mathiasfriman** [comment]
I've been running XD for four days without this occurring again, I think it's safe to close it.
