### ISSUE TITLE
Remove SSH/SFTP support?

### ISSUE THREAD

**Issue by nwmcsween** [majestrate/XD#50]
Would SSH/SFTP be better handled via SSHFS and whatnot?

**Comment by majestrate** [comment]
sshfs is a fuse filesystem, installing that on widows is non trivial.

**Comment by nwmcsween** [comment]
I'm just looking for ways to slim XD down a bit, at 10MB (7MB w/o debug) 
is a bit large for a binary.

**Comment by majestrate** [comment]
go binaries tend to be huge anyways.
