### ISSUE TITLE
Can't remove torrent from webUI

### ISSUE THREAD

**Issue by l-n-s** [majestrate/XD#56]
## info

git revision / version: master

OS: linux

Architecture: x64

## problem

WebUI buttons seems to stop torrent, but don't remove it completely. I had to run ./XD-cli delete [hash] to remove it... After I press remove it shows - "torrent already stopped"

**Comment by majestrate** [comment]
right now the webui stops torrents, i'd prefer to have a dialog box for confirmation for deleting.

**Comment by l-n-s** [comment]
Im implementing confirmation dialog rn. Which action should I trigger after confirmation? delete or remove? What is the difference?

**Comment by majestrate** [comment]
both preferably, like how transmission does it.

**Comment by l-n-s** [comment]
If both, which one goes first? It just seems like the same action to me.

**Comment by l-n-s** [comment]
arrite i did it like i understand, correct if it's wrong
