### ISSUE TITLE
Hardcoded urls in webui

### ISSUE THREAD

**Issue by medspx** [majestrate/XD#57]
## info

git revision / version: master
OS: Debian
Architecture: armhf

## problem
Hello,

I tried to put XD behind a reverse proxy with apache2 mod_proxy, enabling HTTP basic auth.
I need to use a dedicated location (https://myserver/i2pxd/ for example).
Unfortunately, there are some hardlinks towards the API urls in [contrib/webui/lib/main.js](https://github.com/majestrate/XD/blob/9d497b7083bdfe17f5e72fd360c55939c329a0c7/contrib/webui/lib/main.js#L111). I have made some manual modifications into that Javascript file and it seems to fix the problem.

I am no jQuery/JS expert but I think you can just use "/ecksdee/api" as the url in the POST query...

**Comment by majestrate** [comment]
yes that sounds about right. will fix.

**Comment by majestrate** [comment]
what about a relative URL instead of absolute?

**Comment by medspx** [comment]
Hello,

yes, it's better with a relative url. Using _url: "eckdsee/api" does work better!

**Comment by majestrate** [comment]
fixed. used relative url
