### ISSUE TITLE
Feature request: Download speed and progress

### ISSUE THREAD

**Issue by mathiasfriman** [majestrate/XD#6]
As of now, all that is reported is tracker announcement and new peers. No indication of download speed or progress.

For seeding, the peer reporting and announcements are enough, but when downloading, there is no way of knowing how much has been downloaded, and if/when the file(s) are complete. 

A simple (?) listing of **"[torrent hash X]: 159 of 8921 chunks downloaded"** would be a good start to throw in the log once in a while. :) 

Some sort of time delta of downloaded chunks to get a rough estimate of download speed would also be nice, but of secondary importance. 

I'm trying to learn golang in order to help in some way, but for now this is beyond me..

**Comment by majestrate** [comment]
I was planning to have all UI be done via RPC as an external tool, will probably be removing most of those log messages and have them retrieved via rpc.

**Comment by majestrate** [comment]
see issue #2
