### ISSUE TITLE
"ln -s" files and folders to "seeding"

### ISSUE THREAD

**Issue by samalero** [majestrate/XD#63]
## info

git revision / version: 4860eb0

OS: Manjaro Linux

Architecture: amd64

## problem

Please implement linking files to "seeding" folder.

## backtrace / error messages

Error messages: no

Backtrace: no

**Comment by majestrate** [comment]
would the files stay in the download directory or no?

**Comment by samalero** [comment]
no, not enough space. "ln -s" or dynamic folder select for every torrent...

**Comment by majestrate** [comment]
Right now it's a copy then delete, Would it help if I made it a move instead? 
That would cause problems for directories on different filesystems however.

Can do symlinks just fine just thinking if that's the right thing or not.

**Comment by K1773R** [comment]
move or symlink are both nice. copy delete sucks (os will do that anyway, if its a different mount)

**Comment by majestrate** [comment]
alright, i'll have it do a move instead.

**Comment by majestrate** [comment]
looks like the current code does a move not a copy delete, forget when i added that. still want a symlink option?
