### ISSUE TITLE
[Question] Where public GPG key for verification signatures?

### ISSUE THREAD

**Issue by SilmorSenedlen** [majestrate/XD#68]
Good day
Can't found public key by hash(67EF6BA68E7B0B0D6EB4F7D4F357B3B42F6F9B05) even on sks servers.
It would be nice to place it on the main page.

**Comment by majestrate** [comment]
ah yes it's at, https://i2p.rocks/files/jeff.asc

**Comment by majestrate** [comment]
i forgot to publish that key, just pushed it to a public key server.

**Comment by SilmorSenedlen** [comment]
Thx!
