### ISSUE TITLE
Warnings while downloading torrents

### ISSUE THREAD

**Issue by l-n-s** [majestrate/XD#7]
[WRN] 2017-04-04 16:18:16.933835849 +0000 UTC   PutPiece(): error writing book.pdf, write storage/downloads/book.pdf: invalid argument, write 0
    [WRN] 2017-04-04 16:18:16.934857092 +0000 UTC   put piece 814 failed: write storage/downloads/book.pdf: invalid argument
    [WRN] 2017-04-04 16:19:00.997462317 +0000 UTC   PutPiece(): error writing book.pdf, write storage/downloads/book.pdf: invalid argument, write 0
    [WRN] 2017-04-04 16:19:00.998878908 +0000 UTC   put piece 813 failed: write storage/downloads/book.pdf: invalid argument
    [WRN] 2017-04-04 16:19:48.765281032 +0000 UTC   PutPiece(): error writing book.pdf, write storage/downloads/book.pdf: invalid argument, write 0
    [WRN] 2017-04-04 16:19:48.766999915 +0000 UTC   put piece 812 failed: write storage/downloads/book.pdf: invalid argument
    [WRN] 2017-04-04 16:20:19.755607165 +0000 UTC   PutPiece(): error writing book.pdf, write storage/downloads/book.pdf: invalid argument, write 0
    [WRN] 2017-04-04 16:20:19.758052051 +0000 UTC   PutPiece(): error writing book.pdf, write storage/downloads/book.pdf: invalid argument, write 0
    [WRN] 2017-04-04 16:20:19.759014536 +0000 UTC   put piece 811 failed: write storage/downloads/book.pdf: invalid argument
    [WRN] 2017-04-04 16:20:19.759679812 +0000 UTC   put piece 811 failed: write storage/downloads/book.pdf: invalid argument
    [WRN] 2017-04-04 16:22:56.494048112 +0000 UTC   PutPiece(): error writing book.pdf, write storage/downloads/book.pdf: invalid argument, write 0
    [WRN] 2017-04-04 16:22:56.495152534 +0000 UTC   put piece 810 failed: write storage/downloads/book.pdf: invalid argument

And it seems like it stopped downloading after those warnings. Version is trunk from github.

**Comment by majestrate** [comment]
will look into it later today

**Comment by l-n-s** [comment]
Update: Idk if it downloading or not, but it just reported new peer and tracker announce.

Will there be notification in log about successful torrent download?

**Comment by l-n-s** [comment]
Back online. Update on my attempt to download torrent with XD:

    [WRN] 2017-04-05 04:26:28.288427318 +0000 UTC   PutPiece(): error writing Cryptography Theory And Practice - Douglas Stinson
    .pdf, write storage/downloads/Cryptography Theory And Practice - Douglas Stinson.pdf: invalid argument, write 0
    [WRN] 2017-04-05 04:26:28.28858172 +0000 UTC    put piece 13 failed: write storage/downloads/Cryptography Theory And Practic
    e - Douglas Stinson.pdf: invalid argument
    [ERR] 2017-04-05 04:26:30.404353206 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:31:25.483464297 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%03%00%0D5%2Ck%13c%C5 read error: read tcp 
    127.0.0.1:43236->127.0.0.1:7656: read: connection reset by peer
    [ERR] 2017-04-05 04:31:25.484468273 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:31:27.062805658 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%03%11%3F%F8%F6%BF%7F%EE%9A read error: rea
    d tcp 127.0.0.1:43522->127.0.0.1:7656: read: connection reset by peer
    [ERR] 2017-04-05 04:31:27.063458202 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:31:27.109197196 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:31:27.216592388 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:31:38.443105617 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%03%98%DB%82%EE%07%F1J%1D read error: read 
    tcp 127.0.0.1:42640->127.0.0.1:7656: read: connection reset by peer
    [ERR] 2017-04-05 04:31:38.4444524 +0000 UTC     write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:31:46.094332678 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%03n%40%A9C%3A%9A%23%DF read error: read tc
    p 127.0.0.1:43732->127.0.0.1:7656: read: connection reset by peer
    [ERR] 2017-04-05 04:31:46.094791824 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:32:26.927769947 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:32:27.167450539 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:09.439031251 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:09.440918992 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%03%98%DB%82%EE%07%F1J%1D read error: read 
    tcp 127.0.0.1:44016->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:09.440918992 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%03%98%DB%82%EE%07%F1J%1D read er[247/1896]
    tcp 127.0.0.1:44016->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:09.468662153 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%03%99h%D2l%B1%AE%10%98 read error: read tc
    p 127.0.0.1:48658->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:09.468754424 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%03%11%3F%F8%F6%BF%7F%EE%9A read error: rea
    d tcp 127.0.0.1:44006->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:09.46882841 +0000 UTC    %00%00%00%00%00%00%00%00%00%03%03%03%0E%FE%9B6%DEqt%8E read error: read tcp 
    127.0.0.1:36108->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:09.469116634 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%03%7Fu%5D%E7P%26pV read error: read tcp 12
    7.0.0.1:48666->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:09.469182827 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%03%7B%A6%A2%91%9E%F2h%DF read error: read 
    tcp 127.0.0.1:46892->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:09.469427352 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%03%24f%EA%0EyUd%CB read error: read tcp 12
    7.0.0.1:46952->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:09.469527212 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%034%5Dj%C0%EDo%90T read error: read tcp 12
    7.0.0.1:42194->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:09.469943644 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%034%5Dj%C0%EDo%90T read error: read tcp 12
    7.0.0.1:43172->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:09.470084958 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%034%5Dj%C0%EDo%90T read error: read tcp 12
    7.0.0.1:43560->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:09.47014358 +0000 UTC    %00%00%00%00%00%00%00%00%00%03%03%03n%40%A9C%3A%9A%23%DF read error: read tc
    p 127.0.0.1:34300->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:09.470163321 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:09.470217239 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:09.470259788 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:09.470316167 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:09.470350833 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:09.470377651 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:09.470411599 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:09.470435195 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:09.470455915 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:09.470509449 +0000 UTC   write loop ended: %!s(<nil>)
    ....
    [ERR] 2017-04-05 04:33:10.239352276 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:10.239971065 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%03n%40%A9C%3A%9A%23%DF read error: read tc
    p 127.0.0.1:43372->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:10.293201792 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:10.294934044 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%034%5Dj%C0%EDo%90T read error: read tcp 12
    7.0.0.1:43418->127.0.0.1:7656: use of closed network connection
    [ERR] 2017-04-05 04:33:10.391144744 +0000 UTC   write loop ended: %!s(<nil>)
    [ERR] 2017-04-05 04:33:10.392204475 +0000 UTC   %00%00%00%00%00%00%00%00%00%03%03%03%00%0D5%2Ck%13c%C5 read error: read tcp 
    127.0.0.1:43232->127.0.0.1:7656: use of closed network connection
    [NFO] 2017-04-05 04:33:32.211207153 +0000 UTC   Cryptography is seeding

Looks like it has downloaded and seeding, but those errors...


Compared sha1sums with my older download with snark:

    fd8150d4601a23dd18d1800f317f5007a9a4653f  Modern Cryptography Theory and Practice - Wenbo Mao.pdf

with XD:

    12c712ddc486b7a4fe2a506c9cf4d9f9336c97a6  Modern Cryptography Theory and Practice - Wenbo Mao.pdf

File size seems to be correct.

**Comment by majestrate** [comment]
heh, looks like the current revision in master is broken

**Comment by l-n-s** [comment]
Well, I'll wait for the next release and test again if so... would really like to download and seed without bloatware-java :joy:

**Comment by majestrate** [comment]
should be fixed in 0.0.3
