### ISSUE TITLE
Resolver is not exist in go < 1.10.

### ISSUE THREAD

**Issue by r4sas** [majestrate/XD#72]
https://github.com/majestrate/XD/blob/baa497aea9146af703cc56434c2bc02077a19814/src/xd/lib/network/inet/inet.go#L21

:thinking: 
`inet.go:21: undefined: net.Resolver`

```
$ go version
go version go1.7.4 linux/amd64
```

**Comment by sevospl** [comment]
I'm facing the same issue as well.

`src/xd/lib/network/inet/inet.go:21: undefined: net.Resolver
Makefile:58: recipe for target 'XD' failed`

uname -a
`Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux`

go version
`go version go1.7.4 linux/arm`

Any idea on this?

**Comment by l-n-s** [comment]
>Dependencies

>    GNU Make
>    GO 1.6 or higher

Type net.Resolver was added in 1.8, so I guess XD needs to bump go dependency version to 1.8 ?

**Comment by majestrate** [comment]
On Mon, May 27, 2019 at 02:54:52AM -0700, l-n-s wrote:
> >Dependencies
> 
> >    GNU Make
> >    GO 1.6 or higher
> 
> Type net.Resolver was added in 1.8, so I guess XD needs to bump go dependency version to 1.8 ?

yea i believe i do need to

**Comment by sevospl** [comment]
Awesome, I've upgraded Go to the newest version and I was able to compile this. Thanks :)

**Comment by r4sas** [comment]
I think better add vendored version of `net` package.

**Comment by majestrate** [comment]
we could also do a shim layer too @r4sas if you want to code one up

**Comment by l-n-s** [comment]
tbh there's no need to, it's a build-time dependency, and most of the users will use prebuilt binaries anyway
