### ISSUE TITLE
Packaging for debian needs source structure refactoring

### ISSUE THREAD

**Issue by r4sas** [majestrate/XD#74]
For correct packaging in debian, source structure refactor required.

Example of working source tree can be found at https://github.com/r4sas/XD after commit https://github.com/r4sas/XD/commit/2fc71fa0590821bd5e04d8a61cd9c68dc9c6a13b

**Comment by majestrate** [comment]
this has been done, rejoice: https://github.com/majestrate/XD/commit/5c864223210f2848150485a6b40d837e8778575f
