### ISSUE TITLE
XD hangs opening i2p session

### ISSUE THREAD

**Issue by nfisher1226** [majestrate/XD#79]
## info

git revision / version: r24.g07c433d

OS: Arch Linux

Architecture: Armv7l

## problem

Connection is never fully established between XD and i2pd. Works from x86_64, only seeing this problem on Arm.

## backtrace / error messages

Error messages: [yes/no]

[NFO] 2020-04-20 20:54:10.412164129 -0400 EDT m=+0.011105960	starting XD-0.3.3-07c433d
[NFO] 2020-04-20 20:54:10.413647643 -0400 EDT m=+0.012588697	loaded config torrents.ini
[NFO] 2020-04-20 20:54:10.413742901 -0400 EDT m=+0.012683640	Ensure filesystem storage
[NFO] 2020-04-20 20:54:10.414062026 -0400 EDT m=+0.013002561	Swarm netLoop starting
[NFO] 2020-04-20 20:54:10.414188228 -0400 EDT m=+0.013128429	RPC enabled
[NFO] 2020-04-20 20:54:10.415053529 -0400 EDT m=+0.013994027	create new i2p session with <x.x.x.x>:4444
[NFO] 2020-04-20 20:54:10.415260044 -0400 EDT m=+0.014200320	opening i2p session

Last message delivered to console, stays in this state until Sigint sent.

Backtrace: [yes/no]

[insert any backtraces here]

**Comment by majestrate** [comment]
why is it using 4444? isn't that the http proxy port?

**Comment by nfisher1226** [comment]
Wow, that was actually all it was. I apparently edited in the wrong port when editing torrents.ini. Sorry for wasting your time, it's working now.
