### ISSUE TITLE
Make fails on commit e4315ef

### ISSUE THREAD

**Issue by mathiasfriman** [majestrate/XD#8]
Git pulled commit e4315ef and ran **make**

    GOPATH=/home/user/source/go/XD go clean -v
    rm -f storetest rpcdebug
    GOPATH=/home/user/source/go/XD go build -v -ldflags "-X xd/lib/version.Git=-e4315ef"
    github.com/zeebo/bencode
    xd/lib/network
    xd/lib/log
    xd/lib/version
    xd/lib/configparser
    xd/lib/network/i2p
    xd/lib/util
    xd/lib/common
    xd/lib/bittorrent
    xd/lib/bittorrent/extensions
    xd/lib/metainfo
    xd/lib/tracker
    xd/lib/storage
    # xd/lib/tracker
    src/xd/lib/tracker/http.go:52: t.u.Hostname undefined (type *url.URL has no field or method   Hostname)
    src/xd/lib/tracker/http.go:66: t.u.Hostname undefined (type *url.URL has no field or method Hostname)
    src/xd/lib/tracker/http.go:66: t.u.Port undefined (type *url.URL has no field or method Port)
    Makefile:6: recipe for target ”XD” failed
    make: *** [XD] Error 2

EDIT: Saw that the method was implemented in the last commit, and is probably on the way, so you can maybe just ignore this issue..

**Comment by majestrate** [comment]
ah yes, i forgot that i support go 1.3, i'll fix those today.

**Comment by mathiasfriman** [comment]
NP, just a heads up. :) Tried this on go 1.7.1 if that is of any significance whatsoever.

**Comment by majestrate** [comment]
https://github.com/majestrate/XD/commit/b9b2472b130187bdbedb487daffc2d52d525c6d6 should've fixed it, let me know.

**Comment by mathiasfriman** [comment]
Works to compile now. Thanks! :)
