### ISSUE TITLE
Interested in peer w/o pieces

### ISSUE THREAD

**Issue by zzzi2p** [majestrate/XD#80]
## info

0.3.3 as reported to i2psnark.

Architecture: n/a

## problem

XD leech connected to i2psnark who doesn't have any pieces yet.
XD incorrectly indicates interest to the peer when there's nothing to fetch.

## backtrace / error messages

Error messages: no

n/a. As viewed from i2psnark.

Backtrace: no

n/a. As viewed from i2psnark.

**Comment by majestrate** [comment]
allegedly fixed in 0.4.4
