### ISSUE TITLE
webgui port wrong in README.md

### ISSUE THREAD

**Issue by agharbeia** [majestrate/XD#81]
Current README.md states that ```if you compiled with web ui it will be up at http://127.0.0.1:1776/``` while as of this report the port is 1488 as described in https://xd-torrent.readthedocs.io/en/latest/user-guide/run/

**Comment by majestrate** [comment]
the port changed.

**Comment by agharbeia** [comment]
But of course. By reporting the issue, I was hoping you'd change the readme
file.

**Comment by majestrate** [comment]
i dont control the read the docs repo
