### ISSUE TITLE
Makefile: tests no longer run

### ISSUE THREAD

**Issue by dbermond** [majestrate/XD#82]
## info

git revision / version: git master (currently at 6b4204e)

OS: Arch Linux

Architecture: x86_64

## problem

Makefile target `test` no longer run in current git master. It was running fine at tag v0.3.4.

## backtrace / error messages

Error messages: yes

```
$ make
... (build ok)
$ make test
/usr/bin/go test xd/...
go: warning: "xd/..." matched no packages
no packages to test
make: *** [Makefile:71: test] Error 1
```

Backtrace: n/a

**Comment by majestrate** [comment]
fixed in https://github.com/majestrate/XD/commit/151d5b6a13f948b4b3f8728dbb15eecc9e7fc53f

**Comment by dbermond** [comment]
Thank you for the quick fix.

**Comment by majestrate** [comment]
yw
