### ISSUE TITLE
failed to put chunk: read-only filesystem

### ISSUE THREAD

**Issue by nicewaffles** [majestrate/XD#87]
## info

git revision / version: 0.3.4

OS: Arch Linux

Architecture: x86_64

## problem

XD works fine when run as user, but when run as a systemd service it complains about read-only filesystems. I tried making all of the download folders and files have global read/write permissions, but that did not help. Deleting the entire directory and running XD causes it to fail to create the new directory. I suspect that this is a permissions issue, but if chmod 777 on everything didn't work I'm not sure what will.

## backtrace / error messages

Error messages: yes

`failed to put chunk (number): open (full path): read-only filesystem`

Backtrace: no

**Comment by majestrate** [comment]
sounds like your filesystem is read only, no idea.

**Comment by majestrate** [comment]
I don't think I include a systemd service file, but perhaps one of these options is turned on and too restrictive?

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Sandboxing
