### ISSUE TITLE
No bitfield, invalid piece

### ISSUE THREAD

**Issue by mathiasfriman** [majestrate/XD#9]
Just compiled the latest commit. When adding a new torrent, I get:

    [NFO] 2017-05-16 08:15:46.568239734 +0200 CEST	no bitfield for [torrent file]
    [ERR] 2017-05-16 08:15:49.838246699 +0200 CEST	Failed to add [torrent file]: invalid piece

Also, there is a shitload of error messages stating "missing port in address" :

    [WRN] 2017-05-16 08:19:42.034685299 +0200 CEST	 got error while announcing: Get http://w7tpbzncbcocrqtwwm3nezhnnsw4ozadvi2hmvzdhrqzfxfum7wa.b32.i2p/a?downloaded=0&info_hash=%E0%D0xW%15%98%3E%E0O%8C%E5y%B1%D6PT%A3%ACR%F4&ip=np-tl8cbKuImmzkM2sRDFTYfuWgOLafW7~KC-X3vOsXGWDHIp-kSVYLfi~2pjRoET8U~tIvM2ZPXR0SbLuiyPwFf-hPFE3abk9uCfhG~GCtIY9kHqm0xkqCRHyb3llELcrqzTndUCa1MvjcbkoT2LCmFXmKbqbxFZjxQHs3LrCua22EGVNIsUeOTpjf8rZAUjb50N5jlTrW5mNc1o0v-kaJYfGPKGAUmLYbs~6H9Fs9z8xQspjYfYJ-Kk0wVSunF2WZYFte4HyLqLM3jab0SqXorBJ7vHoib2elRcn-pehbozH~-dNoGxc5HD2xUikapvE9Ql4kjGWpVSeqnuPgk8H01X6312MdJ53cVBvcXvcfd2XZJlcgZhIhs0irluu01clrnJQlAZNWTbtKkOHs3sREB3rgatomUz1aFh7CvFU7AF5eOWhSr2wEmZBWHxv2Juhk-9gKHlbw5Y~GAXtP0pT1Z2pkWaHcC3XqAyIu5qJymmK6bSt~C6U2fPLuegEs4AAAA.i2p&left=4344456&numwant=30&peer_id=-XD0030-%1B%FD%CE%F6%96%F5%07%A9%27%9A%B0%9A&port=6881&uploaded=0: missing port in address w7tpbzncbcocrqtwwm3nezhnnsw4ozadvi2hmvzdhrqzfxfum7wa.b32.i2p
    [WRN] 2017-05-16 08:19:42.034729133 +0200 CEST	announce to  failed: Get http://w7tpbzncbcocrqtwwm3nezhnnsw4ozadvi2hmvzdhrqzfxfum7wa.b32.i2p/a?downloaded=0&info_hash=%E0%D0xW%15%98%3E%E0O%8C%E5y%B1%D6PT%A3%ACR%F4&ip=np-tl8cbKuImmzkM2sRDFTYfuWgOLafW7~KC-X3vOsXGWDHIp-kSVYLfi~2pjRoET8U~tIvM2ZPXR0SbLuiyPwFf-hPFE3abk9uCfhG~GCtIY9kHqm0xkqCRHyb3llELcrqzTndUCa1MvjcbkoT2LCmFXmKbqbxFZjxQHs3LrCua22EGVNIsUeOTpjf8rZAUjb50N5jlTrW5mNc1o0v-kaJYfGPKGAUmLYbs~6H9Fs9z8xQspjYfYJ-Kk0wVSunF2WZYFte4HyLqLM3jab0SqXorBJ7vHoib2elRcn-pehbozH~-dNoGxc5HD2xUikapvE9Ql4kjGWpVSeqnuPgk8H01X6312MdJ53cVBvcXvcfd2XZJlcgZhIhs0irluu01clrnJQlAZNWTbtKkOHs3sREB3rgatomUz1aFh7CvFU7AF5eOWhSr2wEmZBWHxv2Juhk-9gKHlbw5Y~GAXtP0pT1Z2pkWaHcC3XqAyIu5qJymmK6bSt~C6U2fPLuegEs4AAAA.i2p&left=4344456&numwant=30&peer_id=-XD0030-%1B%FD%CE%F6%96%F5%07%A9%27%9A%B0%9A&port=6881&uploaded=0: missing port in address w7tpbzncbcocrqtwwm3nezhnnsw4ozadvi2hmvzdhrqzfxfum7wa.b32.i2p

I guess when trying to announce already downloaded torrents.. Not sure if the problem is with the tracker, or with XD though.

**Comment by majestrate** [comment]
yeah i recently borked something in there

**Comment by mathiasfriman** [comment]
Seems like something happened between these commits

    78bbec6eb9ec6fef9e7ac63944de21d043d97537 - OK

    b359f425062b2be2d65562a51954514af43c946c - Shows the error message in the title
